# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27221d7c65c095a261bbebc6b31762f165a73423489278ef551f0d04433d2987a0a8984ed51e2b7be080eb62e2bca3bddd53484e448f9fd3f5c0ff1d980a741

test:
  secret_key_base: f3fcc43a689d09a1afdcefb90b2945aa3c5ae1430aa8e6c0e28be3affad1f46fcb7f0d71fc5fd6143324d66b9613b52978c9c656b3dfa3d010e4940a4099463c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
